name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Configure Git Credentials
    - name: Configure Git Credentials
      uses: actions/checkout@v4
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
      run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV # Cache busting
    
    # Step 3: Cache dependencies
    - name: Cache dependencies
    - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        pip install mkdocs-material
        pip install mkdocs-blogging-plugin
        pip install mkdocs-material-extensions
        pip install mkdocs-glightbox
        pip install mkdocs-rss-plugin

    # Step 4: Build the site
    - name: Build MkDocs site
      run: mkdocs build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
