name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Configure Git user
    - name: Configure Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    # Step 3: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    # Step 4: Cache Python dependencies
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: mkdocs-material-${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          mkdocs-material-${{ runner.os }}-pip-

    # Step 5: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 6: Build the site
    - name: Build MkDocs site
      run: mkdocs build

    # Step 7: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site

    # Step 8: Notify the user with the deployment URL
    - name: Notify deployment URL
      run: |
        echo "Deployed to https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
